//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xyLOGIX.Core.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xyLOGIX.Core.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or the blank string..
        /// </summary>
        public static string Error_ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Error_ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nChars parameter must be greater than zero..
        /// </summary>
        public static string NCharsMustBePositive {
            get {
                return ResourceManager.GetString("NCharsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPersonLastName: Cannot parse empty value for Full Name..
        /// </summary>
        public static string PersonNameEmpty {
            get {
                return ResourceManager.GetString("PersonNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Full Name should at least be two words, separated by a space, such as &apos;&lt;FirstName&gt; &lt;LastName&gt;&apos;..
        /// </summary>
        public static string PersonNameIncorrectFormat {
            get {
                return ResourceManager.GetString("PersonNameIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument of the &apos;count&apos; parameter of the &apos;Left&apos; method must not be greater than the length of the string passed in the &apos;value&apos; parameter, which is {0} character(s)..
        /// </summary>
        public static string StringExtensions_Left_CountMustBeLessThanOrEqualToLengthOfString {
            get {
                return ResourceManager.GetString("StringExtensions_Left_CountMustBeLessThanOrEqualToLengthOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument of the &apos;count&apos; parameter of the &apos;Left&apos; method must be greater than zero..
        /// </summary>
        public static string StringExtensions_Left_CountMustBeNaturalNumber {
            get {
                return ResourceManager.GetString("StringExtensions_Left_CountMustBeNaturalNumber", resourceCulture);
            }
        }
    }
}